const projectData = [
  {
    id: 1,
    name: "Project 1",
    description: "We have worked together to combine two external API's to generate this page. We used a gender guesser and of course, Chuck Norris! Get the API to guess your gender by your name, while also getting a classic Chuck Norris joke!",
    githubLink: "https://github.com/DanielOrnelas01/project-1",
    liveAppLink: "https://danielornelas01.github.io/project-1/",
    imgAlt: "Project 1",
    // photoUrl: require("../../assets/small/portfolio-1.jpg"),
    photoUrl: './project/small/portfolio-1-sm.jpg',
  },
  {
    id: 2,
    name: "Project 2",
    description: "If you love Stephen King, this is the site for you! We have built this site to include all bodies of work by Mr. King for you to peruse, comment on, and like. This is a public community where you can interact with other Stephen King lovers and share your love for horror, terror and all things that go bump in the night!",
    githubLink: "https://github.com/alanam79/The_Kings_Mile",
    liveAppLink: "https://the-kings-mile.herokuapp.com",
    imgAlt: "Project 2",
    photoUrl: './project/small/portfolio-2-sm.jpg',
  },
  {
    id: 3,
    name: "Budget Tracker",
    description: "A budget tracker that allows the user to have offline access to add and remove expenses. Once online access is restored, the users entries are added.",
    githubLink: "https://github.com/alanam79/Budget-Tracker",
    liveAppLink: "https://rocky-bayou-47037.herokuapp.com/",
    imgAlt: "Budget Tracker",
    photoUrl:'./project/small/budget-tracker-sm.jpg',
  },
  {
    id: 4,
    name: "Tech Blog",
    description: "A blog that allows the user to post tech related articles, as well as allow the user to comment on other users blogs.",
    githubLink: "https://github.com/alanam79/Tech-Blog-Challenge",
    liveAppLink: "https://gist.github.com/alanam79/393f2f7e3e008c021b52edb57db5aeea",
    imgAlt: "Tech Blog",
    photoUrl:'./project/small/tech-blog-sm.jpg',
  },
  {
    id: 5,
    name: "Regex Tutorial",
    description: "A tutorial that explains how a specific regular expression, or regex, functions by breaking down each part of the expression and describing what it does.",
    githubLink: "https://github.com/alanam79/Regex-Tutorial",
    liveAppLink: "https://tranquil-shelf-31959.herokuapp.com/",
    imgAlt: "Tech Blog",
    photoUrl:'./project/small/regex-sm.jpg',
  },
  {
    id: 6,
    name: "Social Network API",
    description: "An API for a social network web application where users can share their thoughts, react to friends’ thoughts, and create a friend list. There is no live link, please visit the github to review.",
    githubLink: "https://github.com/alanam79/Social-Network-API",
    // liveAppLink: "https://tranquil-shelf-31959.herokuapp.com/",
    imgAlt: "social Network API",
    photoUrl:'./project/small/social-network-sm.jpg',
  },
];

export default projectData;
